apiVersion: v1
kind: Service
metadata:
  name: customer-api
  namespace: eshop
spec:
  type: ClusterIP
  selector:
    app: customer-api
  ports:
    - name: http
      port: 80
      targetPort: 5011
    - name: grpc
      port: 5022
      targetPort: 5022