apiVersion: v1
kind: Service
metadata:
  name: identity-api
  namespace: eshop
spec:
  type: ClusterIP
  selector:
    app: identity-api
  ports:
    - name: http
      port: 80
      targetPort: 8080