apiVersion: apps/v1
kind: Deployment
metadata:
  name: sql-server
  namespace: eshop
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: sql-server
  template:
    metadata:
      labels:
        app: sql-server
    spec:
      securityContext:
        fsGroup: 10001
      containers:
        - name: sql-server
          image: mcr.microsoft.com/mssql/server:2022-latest
          ports:
            - containerPort: 1433
          env:
            - name: ACCEPT_EULA
              value: "Y"
            - name: MSSQL_PID
              value: "Express"
            - name: MSSQL_SA_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: sql-server-secret
                  key: SA_PASSWORD
          volumeMounts:
            - name: sql-data
              mountPath: /var/opt/mssql
          resources:
            requests:
              memory: "1Gi"
              cpu: "250m"
            limits:
              memory: "2Gi"
              cpu: "1000m"
          readinessProbe:
            tcpSocket:
              port: 1433
            initialDelaySeconds: 20
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 1433
            initialDelaySeconds: 30
            periodSeconds: 30
      volumes:
        - name: sql-data
          persistentVolumeClaim:
            claimName: sql-server-pvc
