apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: eshop-ingress
  namespace: eshop
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /api/products
            pathType: Prefix
            backend:
              service:
                name: catalog-api
                port:
                  number: 80

          - path: /api/categories
            pathType: Prefix
            backend:
              service:
                name: catalog-api
                port:
                  number: 80

          - path: /api/reviews
            pathType: Prefix
            backend:
              service:
                name: catalog-api
                port:
                  number: 80

          - path: /api/customers
            pathType: Prefix
            backend:
              service:
                name: customer-api
                port:
                  number: 80

          - path: /api/orders
            pathType: Prefix
            backend:
              service:
                name: ordering-api
                port:
                  number: 80

          - path: /api/auth
            pathType: Prefix
            backend:
              service:
                name: identity-api
                port:
                  number: 80