apiVersion: v1
kind: ConfigMap
metadata:
  name: ordering-api-config
  namespace: eshop
data:
  ASPNETCORE_ENVIRONMENT: "Production"
  ASPNETCORE_URLS: "http://+:8080"
  Messaging__Provider: "AzureStorageQueue"
  Logging__LogLevel__Default: "Information"
  Logging__LogLevel__Microsoft.AspNetCore: "Warning"