apiVersion: apps/v1
kind: Deployment
metadata:
  name: ordering-api
  namespace: eshop
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: ordering-api
  template:
    metadata:
      labels:
        app: ordering-api
        azure.workload.identity/use: "true"
    spec:
      serviceAccountName: eshop-sa
      containers:
        - name: ordering-api
          image: acreshop2026.azurecr.io/eshop/ordering-api:latest
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: ordering-api-config
          volumeMounts:
            - name: pem-keys
              mountPath: /app/public.pem
              subPath: public.pem
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "500m"
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 10
      volumes:
        - name: pem-keys
          secret:
            secretName: identity-pem-keys