apiVersion: apps/v1
kind: Deployment
metadata:
  name: ordering-api
  namespace: eshop
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ordering-api
  template:
    metadata:
      labels:
        app: ordering-api
    spec:
      initContainers:
        - name: run-migrations
          image: acreshop2026.azurecr.io/eshop/ordering-api:latest
          command: ["dotnet", "ef", "database", "update"]
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: "Production"

      containers:
        - name: ordering-api
          image: acreshop2026.azurecr.io/eshop/ordering-api:latest
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: ordering-api-config
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "500m"
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 10